import type { ToolConfig, ToolSlug } from "@/lib/tools";

export type DirectoryTool = {
  name: string;
  description: string;
  headerDescription?: string;
  category: string;
  href: string;
  iconName: ToolConfig["iconName"];
  accent: string;
};

export function directoryToolSlug(name: string) {
  return name
    .trim()
    .replace(/#/g, "sharp")
    .replace(/\+/g, "plus")
    .replace(/&/g, "and")
    .replace(/[^a-zA-Z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .toLowerCase();
}

const internalToolMap: Partial<Record<ToolSlug, string>> = {
  "code-converter": "Convert code between languages",
  "code-generator": "Generate code from prompts",
  "code-explainer": "Explain unfamiliar code",
  "comment-remover": "Remove code comments",
  "code-checker": "Find code issues",
  "code-to-pdf": "Prepare code documents"
};

export const categories = ["Popular", "Text", "Font Styles", "Encode", "Decode", "Encoding", "Convert", "Utility", "Format", "Beautifiers", "Security", "Network", "Regex", "Code"] as const;

export function getCategoryLabel(category: string) {
  return category === "Text" ? "Text Tools" : category;
}

export function getCategoryId(category: string) {
  return category.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "");
}

const rawDirectoryTools: DirectoryTool[] = [
  { name: "Code Converter", description: internalToolMap["code-converter"]!, category: "Code", href: "/tools/code-converter", iconName: "code", accent: "text-blue-600 bg-blue-50" },
  { name: "Code Generator", description: internalToolMap["code-generator"]!, category: "Code", href: "/tools/code-generator", iconName: "wand", accent: "text-violet-600 bg-violet-50" },
  { name: "Code Explainer", description: internalToolMap["code-explainer"]!, category: "Code", href: "/tools/code-explainer", iconName: "message", accent: "text-cyan-600 bg-cyan-50" },
  { name: "Comment Remover", description: internalToolMap["comment-remover"]!, category: "Format", href: "/tools/comment-remover", iconName: "eraser", accent: "text-rose-600 bg-rose-50" },
  { name: "Code Checker", description: internalToolMap["code-checker"]!, category: "Code", href: "/tools/code-checker", iconName: "bug", accent: "text-amber-600 bg-amber-50" },
  { name: "Code to PDF", description: internalToolMap["code-to-pdf"]!, category: "Convert", href: "/tools/code-to-pdf", iconName: "fileText", accent: "text-emerald-600 bg-emerald-50" },
  { name: "Code Formatter", description: "Format messy code", category: "Code", href: "/tools/code-checker", iconName: "code", accent: "text-indigo-600 bg-indigo-50" },
  { name: "Code Beautifier", description: "Beautify source code", category: "Code", href: "/tools/code-checker", iconName: "wand", accent: "text-sky-600 bg-sky-50" },
  { name: "Code Minifier", description: "Minify source code", category: "Code", href: "/tools/comment-remover", iconName: "eraser", accent: "text-orange-600 bg-orange-50" },
  { name: "Code Diff", description: "Compare code blocks", category: "Code", href: "/tools/code-checker", iconName: "bug", accent: "text-fuchsia-600 bg-fuchsia-50" },
  { name: "Code Snippet Generator", description: "Create small snippets", category: "Code", href: "/tools/code-generator", iconName: "wand", accent: "text-violet-700 bg-violet-50" },
  { name: "Code Commenter", description: "Add helpful comments", category: "Code", href: "/tools/code-generator", iconName: "message", accent: "text-teal-700 bg-teal-50" },
  { name: "Code Refactor", description: "Suggest cleaner code", category: "Code", href: "/tools/code-converter", iconName: "code", accent: "text-blue-700 bg-blue-50" },
  { name: "Code Optimizer", description: "Improve code shape", category: "Code", href: "/tools/code-checker", iconName: "bug", accent: "text-green-700 bg-green-50" },
  { name: "Code Summarizer", description: "Summarize code logic", category: "Code", href: "/tools/code-explainer", iconName: "message", accent: "text-cyan-700 bg-cyan-50" },
  { name: "Code Documentation", description: "Draft code docs", category: "Code", href: "/tools/code-generator", iconName: "fileText", accent: "text-slate-700 bg-slate-100" },
  { name: "Unit Test Generator", description: "Draft unit tests", category: "Code", href: "/tools/code-generator", iconName: "wand", accent: "text-emerald-700 bg-emerald-50" },
  { name: "API Code Generator", description: "Draft API handlers", category: "Code", href: "/tools/code-generator", iconName: "code", accent: "text-purple-700 bg-purple-50" },
  { name: "SQL Query Builder", description: "Build SQL queries", category: "Code", href: "/tools/code-generator", iconName: "code", accent: "text-amber-700 bg-amber-50" },
  { name: "Shell Script Generator", description: "Draft shell scripts", category: "Code", href: "/tools/code-generator", iconName: "fileText", accent: "text-slate-700 bg-slate-100" },
  { name: "Dockerfile Generator", description: "Create Dockerfiles", category: "Code", href: "/tools/code-generator", iconName: "fileText", accent: "text-blue-700 bg-blue-50" },
  { name: "README Generator", description: "Draft README text", category: "Code", href: "/tools/code-generator", iconName: "fileText", accent: "text-gray-700 bg-gray-100" },
  { name: "JSON Viewer", description: "View formatted JSON", category: "Code", href: "/tools/code-checker", iconName: "fileText", accent: "text-emerald-700 bg-emerald-50" },
  { name: "JSON Validator", description: "Validate JSON syntax", category: "Code", href: "/tools/code-checker", iconName: "bug", accent: "text-red-700 bg-red-50" },
  { name: "JSON Editor", description: "Edit and format JSON", category: "Code", href: "/tools/code-checker", iconName: "code", accent: "text-emerald-700 bg-emerald-50" },
  { name: "JSON Path Tester", description: "Test JSONPath queries", category: "Code", href: "/tools/code-checker", iconName: "bug", accent: "text-green-700 bg-green-50" },
  { name: "XML Viewer", description: "View formatted XML", category: "Code", href: "/tools/code-checker", iconName: "fileText", accent: "text-blue-700 bg-blue-50" },
  { name: "XML Validator", description: "Validate XML tags", category: "Code", href: "/tools/code-checker", iconName: "bug", accent: "text-red-700 bg-red-50" },
  { name: "XML Parser", description: "Parse XML elements", category: "Code", href: "/tools/code-explainer", iconName: "message", accent: "text-blue-700 bg-blue-50" },
  { name: "XPath Tester", description: "Test XPath-like paths", category: "Code", href: "/tools/code-checker", iconName: "bug", accent: "text-cyan-700 bg-cyan-50" },
  { name: "YAML Viewer", description: "View YAML data", category: "Code", href: "/tools/code-checker", iconName: "fileText", accent: "text-orange-700 bg-orange-50" },
  { name: "YAML Validator", description: "Validate YAML pairs", category: "Code", href: "/tools/code-checker", iconName: "bug", accent: "text-red-700 bg-red-50" },
  { name: "HTML Viewer", description: "View HTML markup", category: "Code", href: "/tools/code-checker", iconName: "fileText", accent: "text-orange-700 bg-orange-50" },
  { name: "HTML Validator", description: "Validate HTML tags", category: "Code", href: "/tools/code-checker", iconName: "bug", accent: "text-red-700 bg-red-50" },
  { name: "CSS Validator", description: "Validate CSS blocks", category: "Code", href: "/tools/code-checker", iconName: "bug", accent: "text-cyan-700 bg-cyan-50" },
  { name: "JavaScript Validator", description: "Check JavaScript shape", category: "Code", href: "/tools/code-checker", iconName: "bug", accent: "text-yellow-700 bg-yellow-50" },
  { name: "JavaScript Obfuscator", description: "Obfuscate JS strings", category: "Code", href: "/tools/code-converter", iconName: "code", accent: "text-yellow-700 bg-yellow-50" },
  { name: "String to JSON", description: "Parse string as JSON", category: "Code", href: "/tools/code-converter", iconName: "code", accent: "text-emerald-700 bg-emerald-50" },
  { name: "JSON Serialize", description: "Serialize JSON text", category: "Code", href: "/tools/code-converter", iconName: "code", accent: "text-emerald-700 bg-emerald-50" },
  { name: "JSON Deserialize", description: "Deserialize JSON string", category: "Code", href: "/tools/code-converter", iconName: "message", accent: "text-emerald-700 bg-emerald-50" },
  { name: "XML Stringify", description: "Stringify XML markup", category: "Code", href: "/tools/code-converter", iconName: "code", accent: "text-blue-700 bg-blue-50" },
  { name: "Curl to PHP", description: "Convert cURL to PHP", category: "Code", href: "/tools/code-converter", iconName: "code", accent: "text-violet-700 bg-violet-50" },
  { name: "JSON to TypeScript", description: "Generate TS types", category: "Code", href: "/tools/code-generator", iconName: "code", accent: "text-blue-700 bg-blue-50" },
  { name: "JSON to Java", description: "Generate Java class", category: "Code", href: "/tools/code-generator", iconName: "code", accent: "text-orange-700 bg-orange-50" },
  { name: "JSON to Python", description: "Generate Python dataclass", category: "Code", href: "/tools/code-generator", iconName: "code", accent: "text-blue-700 bg-blue-50" },
  { name: "JSON to C#", description: "Generate C# model", category: "Code", href: "/tools/code-generator", iconName: "code", accent: "text-purple-700 bg-purple-50" },
  { name: "JSON Formatter", description: "Format and validate JSON", category: "Popular", href: "/tools/code-checker", iconName: "code", accent: "text-emerald-600 bg-emerald-50" },
  { name: "Base64 Encode", description: "Encode text to Base64", category: "Encode", href: "/tools/code-generator", iconName: "wand", accent: "text-orange-600 bg-orange-50" },
  { name: "Base64 Decode", description: "Decode Base64 text", category: "Decode", href: "/tools/code-explainer", iconName: "message", accent: "text-teal-600 bg-teal-50" },
  { name: "URL Encode", description: "Encode URL strings", category: "Encode", href: "/tools/code-generator", iconName: "code", accent: "text-sky-600 bg-sky-50" },
  { name: "URL Decode", description: "Decode URL strings", category: "Decode", href: "/tools/code-explainer", iconName: "message", accent: "text-blue-600 bg-blue-50" },
  { name: "JavaScript URL Encoder/Decoder", description: "Encode URLs with JS style", category: "Encode", href: "/tools/code-converter", iconName: "code", accent: "text-sky-700 bg-sky-50" },
  { name: "HTML Encode", description: "Escape HTML entities", category: "Encode", href: "/tools/code-converter", iconName: "code", accent: "text-yellow-600 bg-yellow-50" },
  { name: "HTML Decode", description: "Decode HTML entities", category: "Decode", href: "/tools/code-converter", iconName: "code", accent: "text-lime-600 bg-lime-50" },
  { name: "JavaScript Encode", description: "Escape JavaScript strings", category: "Encode", href: "/tools/code-generator", iconName: "code", accent: "text-yellow-700 bg-yellow-50" },
  { name: "JavaScript Decode", description: "Unescape JavaScript strings", category: "Decode", href: "/tools/code-explainer", iconName: "message", accent: "text-yellow-700 bg-yellow-50" },
  { name: "Unicode Encode", description: "Encode text as Unicode escapes", category: "Encode", href: "/tools/code-generator", iconName: "code", accent: "text-violet-600 bg-violet-50" },
  { name: "Unicode Decode", description: "Decode Unicode escape text", category: "Decode", href: "/tools/code-explainer", iconName: "message", accent: "text-violet-600 bg-violet-50" },
  { name: "HTML Entity Encode", description: "Encode reserved HTML characters", category: "Encode", href: "/tools/code-converter", iconName: "code", accent: "text-orange-600 bg-orange-50" },
  { name: "HTML Entity Decode", description: "Decode reserved HTML characters", category: "Decode", href: "/tools/code-converter", iconName: "message", accent: "text-orange-600 bg-orange-50" },
  { name: "JWT Encode", description: "Create JWT-like token text", category: "Encode", href: "/tools/code-generator", iconName: "wand", accent: "text-pink-600 bg-pink-50" },
  { name: "JWT Decode", description: "Decode JWT token sections", category: "Decode", href: "/tools/code-explainer", iconName: "message", accent: "text-pink-600 bg-pink-50" },
  { name: "Quoted Printable Encode", description: "Encode email-safe text", category: "Encode", href: "/tools/code-generator", iconName: "code", accent: "text-amber-700 bg-amber-50" },
  { name: "Quoted Printable Decode", description: "Decode email-safe text", category: "Decode", href: "/tools/code-explainer", iconName: "message", accent: "text-amber-700 bg-amber-50" },
  { name: "Character Encoder/Decoder", description: "Inspect character codes", category: "Encode", href: "/tools/code-converter", iconName: "code", accent: "text-indigo-700 bg-indigo-50" },
  { name: "ISO-8859-1 Garble Decoder", description: "Fix common mojibake text", category: "Decode", href: "/tools/code-converter", iconName: "message", accent: "text-red-700 bg-red-50" },
  { name: "Punycode Encoder/Decoder", description: "Convert international domains", category: "Encode", href: "/tools/code-converter", iconName: "code", accent: "text-green-700 bg-green-50" },
  { name: "UTF-8 Encoder/Decoder", description: "Encode or decode UTF-8 bytes", category: "Encode", href: "/tools/code-converter", iconName: "code", accent: "text-blue-700 bg-blue-50" },
  { name: "UTF-16 Encoder/Decoder", description: "Encode or decode UTF-16 units", category: "Encode", href: "/tools/code-converter", iconName: "code", accent: "text-cyan-700 bg-cyan-50" },
  { name: "UTF-32 Encoder/Decoder", description: "Encode or decode UTF-32 codes", category: "Encode", href: "/tools/code-converter", iconName: "code", accent: "text-purple-700 bg-purple-50" },
  { name: "ROT13 Encoder/Decoder", description: "Apply ROT13 text cipher", category: "Encode", href: "/tools/code-converter", iconName: "code", accent: "text-rose-700 bg-rose-50" },
  { name: "Base32 Encode", description: "Encode text to Base32", category: "Encode", href: "/tools/code-generator", iconName: "wand", accent: "text-cyan-600 bg-cyan-50" },
  { name: "Base32 Decode", description: "Decode Base32 text", category: "Decode", href: "/tools/code-explainer", iconName: "message", accent: "text-cyan-600 bg-cyan-50" },
  { name: "Base58 Encode", description: "Encode text to Base58", category: "Encode", href: "/tools/code-generator", iconName: "wand", accent: "text-blue-600 bg-blue-50" },
  { name: "Base58 Decode", description: "Decode Base58 text", category: "Decode", href: "/tools/code-explainer", iconName: "message", accent: "text-blue-600 bg-blue-50" },
  { name: "Base62 Encoder/Decoder", description: "Convert text with Base62", category: "Encode", href: "/tools/code-converter", iconName: "code", accent: "text-blue-700 bg-blue-50" },
  { name: "Base85 Encoder/Decoder", description: "Convert text with Base85", category: "Encode", href: "/tools/code-converter", iconName: "code", accent: "text-purple-700 bg-purple-50" },
  { name: "Base91 Encoder/Decoder", description: "Convert text with Base91", category: "Encode", href: "/tools/code-converter", iconName: "code", accent: "text-pink-700 bg-pink-50" },
  { name: "Morse Encode", description: "Convert text to Morse code", category: "Encode", href: "/tools/code-generator", iconName: "code", accent: "text-slate-700 bg-slate-100" },
  { name: "Morse Decode", description: "Convert Morse code to text", category: "Decode", href: "/tools/code-explainer", iconName: "message", accent: "text-slate-700 bg-slate-100" },
  { name: "Morse Code Translator", description: "Translate Morse code", category: "Convert", href: "/tools/code-converter", iconName: "message", accent: "text-slate-700 bg-slate-100" },
  { name: "Text Compression Tool", description: "Compress or expand text", category: "Encode", href: "/tools/code-converter", iconName: "code", accent: "text-emerald-700 bg-emerald-50" },
  { name: "Gzip Text Compressor", description: "Preview gzip-style compression", category: "Encode", href: "/tools/code-converter", iconName: "code", accent: "text-emerald-700 bg-emerald-50" },
  { name: "Deflate Text Compressor", description: "Preview deflate-style compression", category: "Encode", href: "/tools/code-converter", iconName: "code", accent: "text-teal-700 bg-teal-50" },
  { name: "Base64 Encode and Decode", description: "Encode or decode Base64", category: "Encode", href: "/tools/code-converter", iconName: "code", accent: "text-orange-700 bg-orange-50" },
  { name: "JSON to Base64", description: "Encode JSON as Base64", category: "Encode", href: "/tools/code-converter", iconName: "code", accent: "text-emerald-700 bg-emerald-50" },
  { name: "Base64 to JSON", description: "Decode Base64 to JSON", category: "Decode", href: "/tools/code-converter", iconName: "message", accent: "text-emerald-700 bg-emerald-50" },
  { name: "XML to Base64", description: "Encode XML as Base64", category: "Encode", href: "/tools/code-converter", iconName: "code", accent: "text-blue-700 bg-blue-50" },
  { name: "Base64 to XML", description: "Decode Base64 to XML", category: "Decode", href: "/tools/code-converter", iconName: "message", accent: "text-blue-700 bg-blue-50" },
  { name: "YAML to Base64", description: "Encode YAML as Base64", category: "Encode", href: "/tools/code-converter", iconName: "code", accent: "text-orange-700 bg-orange-50" },
  { name: "Base64 to YAML", description: "Decode Base64 to YAML", category: "Decode", href: "/tools/code-converter", iconName: "message", accent: "text-orange-700 bg-orange-50" },
  { name: "JSON URL Encode", description: "Encode JSON for URLs", category: "Encode", href: "/tools/code-converter", iconName: "code", accent: "text-emerald-700 bg-emerald-50" },
  { name: "JSON URL Decode", description: "Decode URL JSON text", category: "Decode", href: "/tools/code-converter", iconName: "message", accent: "text-emerald-700 bg-emerald-50" },
  { name: "XML URL Encode", description: "Encode XML for URLs", category: "Encode", href: "/tools/code-converter", iconName: "code", accent: "text-blue-700 bg-blue-50" },
  { name: "XML URL Decode", description: "Decode URL XML text", category: "Decode", href: "/tools/code-converter", iconName: "message", accent: "text-blue-700 bg-blue-50" },
  { name: "YAML URL Encode", description: "Encode YAML for URLs", category: "Encode", href: "/tools/code-converter", iconName: "code", accent: "text-orange-700 bg-orange-50" },
  { name: "YAML URL Decode", description: "Decode URL YAML text", category: "Decode", href: "/tools/code-converter", iconName: "message", accent: "text-orange-700 bg-orange-50" },
  { name: "Encoding List", description: "View common encodings", category: "Encoding", href: "/tools/code-explainer", iconName: "fileText", accent: "text-slate-700 bg-slate-100" },
  { name: "ASCII Code Table", description: "Lookup ASCII codes", category: "Encoding", href: "/tools/code-explainer", iconName: "fileText", accent: "text-blue-700 bg-blue-50" },
  { name: "GB2312 Encoding Table", description: "GB2312 quick reference", category: "Encoding", href: "/tools/code-explainer", iconName: "fileText", accent: "text-red-700 bg-red-50" },
  { name: "GBK Encoding Table", description: "GBK quick reference", category: "Encoding", href: "/tools/code-explainer", iconName: "fileText", accent: "text-orange-700 bg-orange-50" },
  { name: "GB18030 Encoding Rules", description: "GB18030 overview", category: "Encoding", href: "/tools/code-explainer", iconName: "fileText", accent: "text-amber-700 bg-amber-50" },
  { name: "Big5 Encoding Table", description: "Big5 quick reference", category: "Encoding", href: "/tools/code-explainer", iconName: "fileText", accent: "text-pink-700 bg-pink-50" },
  { name: "Unicode Encoding Rules", description: "Unicode code point guide", category: "Encoding", href: "/tools/code-explainer", iconName: "fileText", accent: "text-violet-700 bg-violet-50" },
  { name: "UTF-16 Code Table", description: "UTF-16 quick reference", category: "Encoding", href: "/tools/code-explainer", iconName: "fileText", accent: "text-cyan-700 bg-cyan-50" },
  { name: "Emoji Symbols", description: "Common emoji reference", category: "Encoding", href: "/tools/code-explainer", iconName: "fileText", accent: "text-yellow-700 bg-yellow-50" },
  { name: "Special Symbols", description: "Copy special symbols", category: "Encoding", href: "/tools/code-explainer", iconName: "fileText", accent: "text-purple-700 bg-purple-50" },
  { name: "JavaScript Minifier", description: "Minify JS code", category: "Format", href: "/tools/comment-remover", iconName: "eraser", accent: "text-yellow-700 bg-yellow-50" },
  { name: "CSS Minifier", description: "Minify CSS code", category: "Format", href: "/tools/comment-remover", iconName: "eraser", accent: "text-indigo-600 bg-indigo-50" },
  { name: "Text Diff", description: "Compare two texts", category: "Utility", href: "/tools/code-checker", iconName: "bug", accent: "text-fuchsia-600 bg-fuchsia-50" },
  { name: "JWT Decode", description: "Decode JWT tokens", category: "Security", href: "/tools/code-explainer", iconName: "message", accent: "text-pink-600 bg-pink-50" },
  { name: "Hash Generator", description: "Generate hash values", category: "Security", href: "/tools/code-generator", iconName: "wand", accent: "text-slate-700 bg-slate-100" },
  { name: "Password Generator", description: "Create random passwords", category: "Security", href: "/tools/code-generator", iconName: "wand", accent: "text-amber-600 bg-amber-50" },
  { name: "Caesar Cipher Tool", description: "Shift text with Caesar cipher", category: "Security", href: "/tools/code-converter", iconName: "code", accent: "text-orange-700 bg-orange-50" },
  { name: "MD5 Generator", description: "Generate MD5 hashes", category: "Security", href: "/tools/code-generator", iconName: "wand", accent: "text-slate-700 bg-slate-100" },
  { name: "SHA1 Generator", description: "Generate SHA1 hashes", category: "Security", href: "/tools/code-generator", iconName: "wand", accent: "text-slate-700 bg-slate-100" },
  { name: "SHA256 Generator", description: "Generate SHA256 hashes", category: "Security", href: "/tools/code-generator", iconName: "wand", accent: "text-slate-700 bg-slate-100" },
  { name: "SHA512 Generator", description: "Generate SHA512 hashes", category: "Security", href: "/tools/code-generator", iconName: "wand", accent: "text-slate-700 bg-slate-100" },
  { name: "HMAC Generator", description: "Generate HMAC values", category: "Security", href: "/tools/code-generator", iconName: "wand", accent: "text-blue-700 bg-blue-50" },
  { name: "Hash Identifier", description: "Identify hash types", category: "Security", href: "/tools/code-checker", iconName: "bug", accent: "text-slate-700 bg-slate-100" },
  { name: "Password Strength", description: "Check password strength", category: "Security", href: "/tools/code-checker", iconName: "bug", accent: "text-amber-700 bg-amber-50" },
  { name: "SSL Checker", description: "Inspect SSL details", category: "Security", href: "/tools/code-checker", iconName: "bug", accent: "text-blue-700 bg-blue-50" },
  { name: "WHOIS Lookup", description: "Lookup domain owner", category: "Security", href: "/tools/code-explainer", iconName: "message", accent: "text-slate-700 bg-slate-100" },
  { name: "DNS Lookup", description: "Inspect DNS records", category: "Security", href: "/tools/code-explainer", iconName: "message", accent: "text-cyan-700 bg-cyan-50" },
  { name: "IP Lookup", description: "Lookup IP details", category: "Security", href: "/tools/code-explainer", iconName: "message", accent: "text-indigo-700 bg-indigo-50" },
  { name: "User Agent Parser", description: "Parse user agents", category: "Security", href: "/tools/code-explainer", iconName: "message", accent: "text-slate-700 bg-slate-100" },
  { name: "MD5 Decrypt", description: "Lookup MD5 text", category: "Security", href: "/tools/code-checker", iconName: "bug", accent: "text-red-700 bg-red-50" },
  { name: "Hash Cracker", description: "Mock hash cracking", category: "Security", href: "/tools/code-checker", iconName: "bug", accent: "text-red-700 bg-red-50" },
  { name: "JWT Verify", description: "Verify JWT structure", category: "Security", href: "/tools/code-checker", iconName: "bug", accent: "text-pink-700 bg-pink-50" },
  { name: "URL Scanner", description: "Scan URL text", category: "Security", href: "/tools/code-checker", iconName: "bug", accent: "text-blue-700 bg-blue-50" },
  { name: "Security Headers", description: "Check header policy", category: "Security", href: "/tools/code-checker", iconName: "bug", accent: "text-slate-700 bg-slate-100" },
  { name: "QR Code Generator", description: "Create QR payload text", category: "Utility", href: "/tools/code-generator", iconName: "wand", accent: "text-slate-700 bg-slate-100" },
  { name: "Lorem Ipsum", description: "Generate filler text", category: "Utility", href: "/tools/code-generator", iconName: "wand", accent: "text-green-600 bg-green-50" },
  { name: "Text Compare", description: "Compare text blocks", category: "Utility", href: "/tools/code-checker", iconName: "bug", accent: "text-violet-600 bg-violet-50" },
  { name: "File Difference Tool", description: "Compare file text", category: "Utility", href: "/tools/code-checker", iconName: "bug", accent: "text-violet-700 bg-violet-50" },
  { name: "JSON Diff Tool", description: "Compare JSON objects", category: "Utility", href: "/tools/code-checker", iconName: "bug", accent: "text-emerald-700 bg-emerald-50" },
  { name: "XML Diff Tool", description: "Compare XML markup", category: "Utility", href: "/tools/code-checker", iconName: "bug", accent: "text-blue-700 bg-blue-50" },
  { name: "Word Counter", description: "Count words quickly", category: "Utility", href: "/tools/code-checker", iconName: "fileText", accent: "text-cyan-600 bg-cyan-50" },
  { name: "Character Counter", description: "Count characters", category: "Utility", href: "/tools/code-checker", iconName: "fileText", accent: "text-emerald-600 bg-emerald-50" },
  { name: "Line Counter", description: "Count text lines", category: "Utility", href: "/tools/code-checker", iconName: "fileText", accent: "text-slate-700 bg-slate-100" },
  { name: "Case Converter", description: "Change text case", category: "Utility", href: "/tools/code-converter", iconName: "code", accent: "text-teal-600 bg-teal-50" },
  { name: "Number Sorter", description: "Sort numbers quickly", category: "Utility", href: "/tools/code-checker", iconName: "fileText", accent: "text-indigo-700 bg-indigo-50" },
  { name: "Base Number Converter", description: "Convert numbers across bases", category: "Convert", href: "/tools/code-converter", iconName: "code", accent: "text-indigo-700 bg-indigo-50" },
  { name: "BigInt Base Converter", description: "Convert large integer bases", category: "Convert", href: "/tools/code-converter", iconName: "code", accent: "text-violet-700 bg-violet-50" },
  { name: "IEEE 754 Float Converter", description: "Convert floats to hex bits", category: "Convert", href: "/tools/code-converter", iconName: "code", accent: "text-cyan-700 bg-cyan-50" },
  { name: "Byte Signed Unsigned Converter", description: "Convert byte number signs", category: "Convert", href: "/tools/code-converter", iconName: "code", accent: "text-orange-700 bg-orange-50" },
  { name: "Little Big Endian Converter", description: "Reverse byte endianness", category: "Convert", href: "/tools/code-converter", iconName: "code", accent: "text-amber-700 bg-amber-50" },
  { name: "Reverse Binary Tool", description: "Reverse binary bits", category: "Convert", href: "/tools/code-converter", iconName: "code", accent: "text-slate-700 bg-slate-100" },
  { name: "Reverse Array Tool", description: "Reverse array items", category: "Utility", href: "/tools/code-converter", iconName: "code", accent: "text-teal-700 bg-teal-50" },
  { name: "Barcode Generator", description: "Create barcode text", category: "Utility", href: "/tools/code-generator", iconName: "wand", accent: "text-slate-700 bg-slate-100" },
  { name: "Slug Generator", description: "Make URL slugs", category: "Utility", href: "/tools/code-generator", iconName: "wand", accent: "text-amber-700 bg-amber-50" },
  { name: "Slugify URL Generator", description: "Create URL-friendly slugs", category: "Utility", href: "/tools/code-generator", iconName: "wand", accent: "text-amber-700 bg-amber-50" },
  { name: "UTM Generator", description: "Build campaign URLs", category: "Utility", href: "/tools/code-generator", iconName: "wand", accent: "text-blue-700 bg-blue-50" },
  { name: "URL Parameter Formatter", description: "Format URL query strings", category: "Network", href: "/tools/code-explainer", iconName: "message", accent: "text-blue-700 bg-blue-50" },
  { name: "URL Batch Generator", description: "Generate URL batches", category: "Network", href: "/tools/code-generator", iconName: "wand", accent: "text-green-700 bg-green-50" },
  { name: "HTACCESS Generator", description: "Draft htaccess rules", category: "Utility", href: "/tools/code-generator", iconName: "fileText", accent: "text-blue-600 bg-blue-50" },
  { name: "Cron Generator", description: "Build cron syntax", category: "Utility", href: "/tools/code-generator", iconName: "code", accent: "text-slate-700 bg-slate-100" },
  { name: "Cron Expression Parser", description: "Explain cron syntax", category: "Utility", href: "/tools/code-explainer", iconName: "message", accent: "text-slate-700 bg-slate-100" },
  { name: "Text Reverser", description: "Reverse text order", category: "Utility", href: "/tools/code-converter", iconName: "code", accent: "text-violet-600 bg-violet-50" },
  { name: "Remove Duplicates", description: "Deduplicate lines", category: "Utility", href: "/tools/code-checker", iconName: "eraser", accent: "text-blue-600 bg-blue-50" },
  { name: "Sort Lines", description: "Sort text lines", category: "Utility", href: "/tools/code-checker", iconName: "fileText", accent: "text-cyan-600 bg-cyan-50" },
  { name: "Lorem Faker", description: "Fake content data", category: "Utility", href: "/tools/code-generator", iconName: "wand", accent: "text-fuchsia-600 bg-fuchsia-50" },
  { name: "CSV to JSON", description: "Convert CSV data", category: "Convert", href: "/tools/code-converter", iconName: "code", accent: "text-green-600 bg-green-50" },
  { name: "JSON to CSV", description: "Convert JSON arrays", category: "Convert", href: "/tools/code-converter", iconName: "code", accent: "text-green-600 bg-green-50" },
  { name: "JSON Escape Tool", description: "Escape and unescape JSON", category: "Convert", href: "/tools/code-converter", iconName: "code", accent: "text-emerald-700 bg-emerald-50" },
  { name: "JSON URL Parameters Converter", description: "Convert JSON and query params", category: "Convert", href: "/tools/code-converter", iconName: "code", accent: "text-blue-700 bg-blue-50" },
  { name: "JSON to Model Generator", description: "Generate typed model code", category: "Code", href: "/tools/code-generator", iconName: "code", accent: "text-purple-700 bg-purple-50" },
  { name: "Markdown to HTML", description: "Convert Markdown", category: "Convert", href: "/tools/code-converter", iconName: "code", accent: "text-blue-600 bg-blue-50" },
  { name: "HTML to Markdown", description: "Convert HTML", category: "Convert", href: "/tools/code-converter", iconName: "code", accent: "text-cyan-600 bg-cyan-50" },
  { name: "Word to Markdown Converter", description: "Convert text to Markdown", category: "Convert", href: "/tools/code-converter", iconName: "fileText", accent: "text-blue-700 bg-blue-50" },
  { name: "JSON to XML", description: "Convert JSON to XML", category: "Convert", href: "/tools/code-converter", iconName: "code", accent: "text-emerald-600 bg-emerald-50" },
  { name: "XML to JSON", description: "Convert XML to JSON", category: "Convert", href: "/tools/code-converter", iconName: "code", accent: "text-blue-600 bg-blue-50" },
  { name: "YAML to JSON", description: "Convert YAML to JSON", category: "Convert", href: "/tools/code-converter", iconName: "code", accent: "text-orange-600 bg-orange-50" },
  { name: "JSON to YAML", description: "Convert JSON to YAML", category: "Convert", href: "/tools/code-converter", iconName: "code", accent: "text-orange-600 bg-orange-50" },
  { name: "JSON Stringify Text", description: "Escape text as JSON string", category: "Convert", href: "/tools/code-converter", iconName: "code", accent: "text-emerald-700 bg-emerald-50" },
  { name: "JSON Unstringifier", description: "Unescape JSON strings", category: "Convert", href: "/tools/code-converter", iconName: "message", accent: "text-emerald-700 bg-emerald-50" },
  { name: "TOML to JSON", description: "Convert TOML to JSON", category: "Convert", href: "/tools/code-converter", iconName: "code", accent: "text-slate-700 bg-slate-100" },
  { name: "JSON to TOML", description: "Convert JSON to TOML", category: "Convert", href: "/tools/code-converter", iconName: "code", accent: "text-slate-700 bg-slate-100" },
  { name: "INI to JSON", description: "Convert INI to JSON", category: "Convert", href: "/tools/code-converter", iconName: "code", accent: "text-teal-600 bg-teal-50" },
  { name: "JSON to INI", description: "Convert JSON to INI", category: "Convert", href: "/tools/code-converter", iconName: "code", accent: "text-teal-600 bg-teal-50" },
  { name: "JSON to TSV", description: "Convert JSON to TSV", category: "Convert", href: "/tools/code-converter", iconName: "code", accent: "text-emerald-700 bg-emerald-50" },
  { name: "TSV to JSON", description: "Convert TSV to JSON", category: "Convert", href: "/tools/code-converter", iconName: "code", accent: "text-emerald-700 bg-emerald-50" },
  { name: "Text to CSV", description: "Convert plain text to CSV", category: "Convert", href: "/tools/code-converter", iconName: "fileText", accent: "text-green-600 bg-green-50" },
  { name: "CSV to Text", description: "Convert CSV to plain text", category: "Convert", href: "/tools/code-converter", iconName: "fileText", accent: "text-green-600 bg-green-50" },
  { name: "CSV to XML", description: "Convert CSV to XML", category: "Convert", href: "/tools/code-converter", iconName: "code", accent: "text-green-700 bg-green-50" },
  { name: "XML to CSV", description: "Convert XML to CSV", category: "Convert", href: "/tools/code-converter", iconName: "code", accent: "text-blue-700 bg-blue-50" },
  { name: "CSV to YAML", description: "Convert CSV to YAML", category: "Convert", href: "/tools/code-converter", iconName: "code", accent: "text-orange-700 bg-orange-50" },
  { name: "YAML to CSV", description: "Convert YAML to CSV", category: "Convert", href: "/tools/code-converter", iconName: "code", accent: "text-orange-700 bg-orange-50" },
  { name: "XML to YAML", description: "Convert XML to YAML", category: "Convert", href: "/tools/code-converter", iconName: "code", accent: "text-cyan-700 bg-cyan-50" },
  { name: "YAML to XML", description: "Convert YAML to XML", category: "Convert", href: "/tools/code-converter", iconName: "code", accent: "text-cyan-700 bg-cyan-50" },
  { name: "File Hex Converter", description: "Convert text and hex bytes", category: "Convert", href: "/tools/code-converter", iconName: "fileText", accent: "text-red-700 bg-red-50" },
  { name: "HEX to RGB", description: "Convert HEX colors to RGB", category: "Convert", href: "/tools/code-converter", iconName: "code", accent: "text-rose-600 bg-rose-50" },
  { name: "RGB to HEX", description: "Convert RGB colors to HEX", category: "Convert", href: "/tools/code-converter", iconName: "code", accent: "text-rose-600 bg-rose-50" },
  { name: "Text to HEX", description: "Encode text as HEX", category: "Convert", href: "/tools/code-converter", iconName: "code", accent: "text-red-600 bg-red-50" },
  { name: "HEX to Text", description: "Decode HEX to text", category: "Convert", href: "/tools/code-converter", iconName: "message", accent: "text-red-600 bg-red-50" },
  { name: "Decimal to HEX", description: "Convert decimal numbers to HEX", category: "Convert", href: "/tools/code-converter", iconName: "code", accent: "text-amber-700 bg-amber-50" },
  { name: "HEX to Decimal", description: "Convert HEX numbers to decimal", category: "Convert", href: "/tools/code-converter", iconName: "message", accent: "text-amber-700 bg-amber-50" },
  { name: "Binary Code Translator", description: "Translate binary code", headerDescription: "Convert plain text to binary code or translate binary code back into readable text using a simple online binary translator.", category: "Convert", href: "/tools/code-converter", iconName: "code", accent: "text-slate-700 bg-slate-100" },
  { name: "Binary to Text", description: "Convert binary to text", category: "Convert", href: "/tools/code-converter", iconName: "message", accent: "text-slate-700 bg-slate-100" },
  { name: "Text to Binary", description: "Convert text to binary", category: "Convert", href: "/tools/code-converter", iconName: "code", accent: "text-slate-700 bg-slate-100" },
  { name: "Octal to Decimal", description: "Convert octal numbers", category: "Convert", href: "/tools/code-converter", iconName: "message", accent: "text-indigo-600 bg-indigo-50" },
  { name: "Decimal to Octal", description: "Convert decimal to octal", category: "Convert", href: "/tools/code-converter", iconName: "code", accent: "text-indigo-600 bg-indigo-50" },
  { name: "Unix to Date", description: "Convert Unix timestamp to date", category: "Convert", href: "/tools/code-converter", iconName: "fileText", accent: "text-lime-700 bg-lime-50" },
  { name: "Date to Unix", description: "Convert date to Unix timestamp", category: "Convert", href: "/tools/code-converter", iconName: "fileText", accent: "text-lime-700 bg-lime-50" },
  { name: "HTML to Text", description: "Strip HTML into text", category: "Convert", href: "/tools/code-converter", iconName: "message", accent: "text-cyan-600 bg-cyan-50" },
  { name: "Text to HTML", description: "Convert text to HTML", category: "Convert", href: "/tools/code-converter", iconName: "code", accent: "text-cyan-600 bg-cyan-50" },
  { name: "Escape HTML", description: "Escape HTML markup", category: "Convert", href: "/tools/code-converter", iconName: "code", accent: "text-yellow-600 bg-yellow-50" },
  { name: "Unescape HTML", description: "Unescape HTML markup", category: "Convert", href: "/tools/code-converter", iconName: "message", accent: "text-yellow-600 bg-yellow-50" },
  { name: "CSS to Inline", description: "Convert CSS rules to inline styles", category: "Convert", href: "/tools/code-converter", iconName: "code", accent: "text-blue-600 bg-blue-50" },
  { name: "Inline to CSS", description: "Extract inline styles to CSS", category: "Convert", href: "/tools/code-converter", iconName: "message", accent: "text-blue-600 bg-blue-50" },
  { name: "CSS to SCSS", description: "Convert CSS to SCSS", category: "Convert", href: "/tools/code-converter", iconName: "code", accent: "text-pink-700 bg-pink-50" },
  { name: "SCSS to CSS", description: "Convert SCSS to CSS", category: "Convert", href: "/tools/code-converter", iconName: "code", accent: "text-pink-700 bg-pink-50" },
  { name: "CSS to LESS", description: "Convert CSS to LESS", category: "Convert", href: "/tools/code-converter", iconName: "code", accent: "text-indigo-700 bg-indigo-50" },
  { name: "LESS to CSS", description: "Convert LESS to CSS", category: "Convert", href: "/tools/code-converter", iconName: "code", accent: "text-indigo-700 bg-indigo-50" },
  { name: "CSS to SASS", description: "Convert CSS to SASS", category: "Convert", href: "/tools/code-converter", iconName: "code", accent: "text-rose-700 bg-rose-50" },
  { name: "SASS to CSS", description: "Convert SASS to CSS", category: "Convert", href: "/tools/code-converter", iconName: "code", accent: "text-rose-700 bg-rose-50" },
  { name: "LESS to SCSS", description: "Convert LESS to SCSS", category: "Convert", href: "/tools/code-converter", iconName: "code", accent: "text-purple-700 bg-purple-50" },
  { name: "SCSS to LESS", description: "Convert SCSS to LESS", category: "Convert", href: "/tools/code-converter", iconName: "code", accent: "text-purple-700 bg-purple-50" },
  { name: "Stylus to CSS", description: "Convert Stylus to CSS", category: "Convert", href: "/tools/code-converter", iconName: "code", accent: "text-green-700 bg-green-50" },
  { name: "CSS to Stylus", description: "Convert CSS to Stylus", category: "Convert", href: "/tools/code-converter", iconName: "code", accent: "text-green-700 bg-green-50" },
  { name: "Base64 to Text", description: "Decode Base64 text", category: "Decode", href: "/tools/code-converter", iconName: "message", accent: "text-orange-700 bg-orange-50" },
  { name: "Text to Base64", description: "Encode text as Base64", category: "Encode", href: "/tools/code-converter", iconName: "code", accent: "text-orange-700 bg-orange-50" },
  { name: "SQL Formatter", description: "Format SQL queries", category: "Format", href: "/tools/code-checker", iconName: "code", accent: "text-violet-600 bg-violet-50" },
  { name: "GraphQL Formatter", description: "Format GraphQL queries", category: "Format", href: "/tools/code-checker", iconName: "code", accent: "text-pink-700 bg-pink-50" },
  { name: "Nginx Formatter", description: "Format Nginx config", category: "Format", href: "/tools/code-checker", iconName: "code", accent: "text-green-700 bg-green-50" },
  { name: "Python Formatter", description: "Format Python code", category: "Format", href: "/tools/code-checker", iconName: "code", accent: "text-blue-600 bg-blue-50" },
  { name: "JSON Formatter", description: "Format JSON data", category: "Format", href: "/tools/code-checker", iconName: "code", accent: "text-emerald-600 bg-emerald-50" },
  { name: "JSON5 Formatter", description: "Format JSON5 data", category: "Format", href: "/tools/code-checker", iconName: "code", accent: "text-emerald-700 bg-emerald-50" },
  { name: "JSON5 Validator", description: "Validate JSON5 text", category: "Format", href: "/tools/code-checker", iconName: "bug", accent: "text-red-700 bg-red-50" },
  { name: "XML Formatter", description: "Format XML markup", category: "Format", href: "/tools/code-checker", iconName: "code", accent: "text-blue-600 bg-blue-50" },
  { name: "HTML Formatter", description: "Format HTML markup", category: "Format", href: "/tools/code-checker", iconName: "code", accent: "text-orange-600 bg-orange-50" },
  { name: "CSS Formatter", description: "Format CSS code", category: "Format", href: "/tools/code-checker", iconName: "code", accent: "text-cyan-600 bg-cyan-50" },
  { name: "SCSS Formatter", description: "Format SCSS code", category: "Format", href: "/tools/code-checker", iconName: "code", accent: "text-pink-700 bg-pink-50" },
  { name: "JavaScript Formatter", description: "Format JS code", category: "Format", href: "/tools/code-checker", iconName: "code", accent: "text-yellow-700 bg-yellow-50" },
  { name: "TypeScript Formatter", description: "Format TypeScript code", category: "Format", href: "/tools/code-checker", iconName: "code", accent: "text-blue-700 bg-blue-50" },
  { name: "React Formatter", description: "Format React code", category: "Format", href: "/tools/code-checker", iconName: "code", accent: "text-sky-700 bg-sky-50" },
  { name: "Angular Formatter", description: "Format Angular code", category: "Format", href: "/tools/code-checker", iconName: "code", accent: "text-red-700 bg-red-50" },
  { name: "Vue JS Formatter", description: "Format Vue code", category: "Format", href: "/tools/code-checker", iconName: "code", accent: "text-green-700 bg-green-50" },
  { name: "Babel Formatter", description: "Format Babel output", category: "Format", href: "/tools/code-checker", iconName: "code", accent: "text-yellow-700 bg-yellow-50" },
  { name: "MDX Formatter", description: "Format MDX content", category: "Format", href: "/tools/code-checker", iconName: "fileText", accent: "text-purple-700 bg-purple-50" },
  { name: "Glimmer JS Formatter", description: "Format Glimmer code", category: "Format", href: "/tools/code-checker", iconName: "code", accent: "text-orange-700 bg-orange-50" },
  { name: "LWC Formatter", description: "Format Lightning Web Components", category: "Format", href: "/tools/code-checker", iconName: "code", accent: "text-sky-700 bg-sky-50" },
  { name: "LESS Formatter", description: "Format LESS code", category: "Format", href: "/tools/code-checker", iconName: "code", accent: "text-indigo-700 bg-indigo-50" },
  { name: "PHP Formatter", description: "Format PHP code", category: "Format", href: "/tools/code-checker", iconName: "code", accent: "text-violet-600 bg-violet-50" },
  { name: "WSDL Formatter", description: "Format WSDL XML documents", category: "Format", href: "/tools/code-checker", iconName: "code", accent: "text-blue-700 bg-blue-50" },
  { name: "SOAP Formatter", description: "Format SOAP XML envelopes", category: "Format", href: "/tools/code-checker", iconName: "code", accent: "text-cyan-700 bg-cyan-50" },
  { name: "Flow Formatter", description: "Format Flow typed JavaScript", category: "Format", href: "/tools/code-checker", iconName: "code", accent: "text-indigo-700 bg-indigo-50" },
  { name: "Java Formatter", description: "Format Java code", category: "Format", href: "/tools/code-checker", iconName: "code", accent: "text-orange-600 bg-orange-50" },
  { name: "C# Formatter", description: "Format C# code", category: "Format", href: "/tools/code-checker", iconName: "code", accent: "text-cyan-700 bg-cyan-50" },
  { name: "C/C++ Formatter", description: "Format C/C++ code", category: "Format", href: "/tools/code-checker", iconName: "code", accent: "text-blue-700 bg-blue-50" },
  { name: "Go Formatter", description: "Format Go code", category: "Format", href: "/tools/code-checker", iconName: "code", accent: "text-sky-600 bg-sky-50" },
  { name: "Markdown Formatter", description: "Format Markdown text", category: "Format", href: "/tools/code-checker", iconName: "fileText", accent: "text-slate-700 bg-slate-100" },
  { name: "YAML Formatter", description: "Format YAML text", category: "Format", href: "/tools/code-checker", iconName: "fileText", accent: "text-orange-700 bg-orange-50" },
  { name: "Minify HTML", description: "Minify HTML markup", category: "Format", href: "/tools/comment-remover", iconName: "eraser", accent: "text-orange-600 bg-orange-50" },
  { name: "Minify JSON", description: "Minify JSON data", category: "Format", href: "/tools/comment-remover", iconName: "eraser", accent: "text-emerald-600 bg-emerald-50" },
  { name: "Minify XML", description: "Minify XML markup", category: "Format", href: "/tools/comment-remover", iconName: "eraser", accent: "text-blue-600 bg-blue-50" },
  { name: "SQL Minifier", description: "Minify SQL queries", category: "Format", href: "/tools/comment-remover", iconName: "eraser", accent: "text-violet-700 bg-violet-50" },
  { name: "Lua Minifier", description: "Minify Lua code", category: "Format", href: "/tools/comment-remover", iconName: "eraser", accent: "text-blue-700 bg-blue-50" },
  { name: "Text Minifier", description: "Minify plain text", category: "Format", href: "/tools/comment-remover", iconName: "eraser", accent: "text-slate-700 bg-slate-100" },
  { name: "Remove Comments", description: "Remove code comments", category: "Format", href: "/tools/comment-remover", iconName: "eraser", accent: "text-rose-600 bg-rose-50" },
  { name: "Add Line Numbers", description: "Number code lines", category: "Format", href: "/tools/code-generator", iconName: "fileText", accent: "text-slate-700 bg-slate-100" },
  { name: "Text Wrap", description: "Wrap long text", category: "Format", href: "/tools/code-converter", iconName: "fileText", accent: "text-violet-600 bg-violet-50" },
  { name: "JSON Beautifier", description: "Beautify JSON data", category: "Beautifiers", href: "/tools/code-checker", iconName: "wand", accent: "text-emerald-700 bg-emerald-50" },
  { name: "CSS Beautifier", description: "Beautify CSS", category: "Beautifiers", href: "/tools/code-checker", iconName: "wand", accent: "text-cyan-600 bg-cyan-50" },
  { name: "XML Beautifier", description: "Beautify XML", category: "Beautifiers", href: "/tools/code-checker", iconName: "wand", accent: "text-blue-600 bg-blue-50" },
  { name: "HTML Beautifier", description: "Beautify HTML", category: "Beautifiers", href: "/tools/code-checker", iconName: "wand", accent: "text-orange-600 bg-orange-50" },
  { name: "JavaScript Beautifier", description: "Beautify JavaScript", category: "Beautifiers", href: "/tools/code-checker", iconName: "wand", accent: "text-yellow-700 bg-yellow-50" },
  { name: "YAML Beautifier", description: "Beautify YAML text", category: "Beautifiers", href: "/tools/code-checker", iconName: "wand", accent: "text-orange-700 bg-orange-50" },
  { name: "C# Beautifier", description: "Beautify C# code", category: "Beautifiers", href: "/tools/code-checker", iconName: "wand", accent: "text-cyan-700 bg-cyan-50" },
  { name: "Java Beautifier", description: "Beautify Java code", category: "Beautifiers", href: "/tools/code-checker", iconName: "wand", accent: "text-orange-700 bg-orange-50" },
  { name: "C Beautifier", description: "Beautify C code", category: "Beautifiers", href: "/tools/code-checker", iconName: "wand", accent: "text-sky-700 bg-sky-50" },
  { name: "C++ Beautifier", description: "Beautify C++ code", category: "Beautifiers", href: "/tools/code-checker", iconName: "wand", accent: "text-blue-700 bg-blue-50" },
  { name: "LESS Beautifier", description: "Beautify LESS code", category: "Beautifiers", href: "/tools/code-checker", iconName: "wand", accent: "text-indigo-700 bg-indigo-50" },
  { name: "SCSS Beautifier", description: "Beautify SCSS code", category: "Beautifiers", href: "/tools/code-checker", iconName: "wand", accent: "text-pink-700 bg-pink-50" },
  { name: "GraphQL Beautifier", description: "Beautify GraphQL queries", category: "Beautifiers", href: "/tools/code-checker", iconName: "wand", accent: "text-pink-700 bg-pink-50" },
  { name: "PHP Beautifier", description: "Beautify PHP code", category: "Beautifiers", href: "/tools/code-checker", iconName: "wand", accent: "text-violet-700 bg-violet-50" },
  { name: "Python Beautifier", description: "Beautify Python code", category: "Beautifiers", href: "/tools/code-checker", iconName: "wand", accent: "text-blue-700 bg-blue-50" },
  { name: "Perl Beautifier", description: "Beautify Perl code", category: "Beautifiers", href: "/tools/code-checker", iconName: "wand", accent: "text-blue-700 bg-blue-50" },
  { name: "Ruby Beautifier", description: "Beautify Ruby code", category: "Beautifiers", href: "/tools/code-checker", iconName: "wand", accent: "text-red-700 bg-red-50" },
  { name: "Lua Beautifier", description: "Beautify Lua code", category: "Beautifiers", href: "/tools/code-checker", iconName: "wand", accent: "text-blue-700 bg-blue-50" },
  { name: "XAML Beautifier", description: "Beautify XAML markup", category: "Beautifiers", href: "/tools/code-checker", iconName: "wand", accent: "text-purple-700 bg-purple-50" },
  { name: "Regex Tester", description: "Test regex matches", category: "Regex", href: "/tools/code-checker", iconName: "bug", accent: "text-slate-700 bg-slate-100" },
  { name: "Regex Generator", description: "Draft regex patterns", category: "Regex", href: "/tools/code-generator", iconName: "wand", accent: "text-violet-600 bg-violet-50" },
  { name: "Regex Cheat Sheet", description: "Quick regex syntax", category: "Regex", href: "/tools/code-explainer", iconName: "fileText", accent: "text-blue-700 bg-blue-50" },
  { name: "Regex Extractor", description: "Extract matching text", category: "Regex", href: "/tools/code-generator", iconName: "code", accent: "text-cyan-700 bg-cyan-50" },
  { name: "Regex Replace", description: "Replace by pattern", category: "Regex", href: "/tools/code-converter", iconName: "eraser", accent: "text-rose-600 bg-rose-50" },
  { name: "Regex Split", description: "Split text by regex", category: "Regex", href: "/tools/code-converter", iconName: "code", accent: "text-indigo-700 bg-indigo-50" },
  { name: "Regex Escape", description: "Escape regex chars", category: "Regex", href: "/tools/code-converter", iconName: "code", accent: "text-amber-700 bg-amber-50" },
  { name: "Regex Unescape", description: "Unescape regex text", category: "Regex", href: "/tools/code-converter", iconName: "message", accent: "text-amber-700 bg-amber-50" },
  { name: "Regex Explainer", description: "Explain pattern parts", category: "Regex", href: "/tools/code-explainer", iconName: "message", accent: "text-teal-700 bg-teal-50" },
  { name: "Regex Matcher", description: "List every match", category: "Regex", href: "/tools/code-checker", iconName: "bug", accent: "text-emerald-700 bg-emerald-50" },
  { name: "Regex Validator", description: "Validate regex syntax", category: "Regex", href: "/tools/code-checker", iconName: "bug", accent: "text-green-700 bg-green-50" },
  { name: "Regex Groups", description: "Show capture groups", category: "Regex", href: "/tools/code-checker", iconName: "bug", accent: "text-purple-700 bg-purple-50" },
  { name: "Email Regex", description: "Match email strings", category: "Regex", href: "/tools/code-generator", iconName: "wand", accent: "text-pink-700 bg-pink-50" },
  { name: "URL Regex", description: "Match web links", category: "Regex", href: "/tools/code-generator", iconName: "wand", accent: "text-blue-700 bg-blue-50" },
  { name: "Phone Regex", description: "Match phone numbers", category: "Regex", href: "/tools/code-generator", iconName: "wand", accent: "text-orange-700 bg-orange-50" },
  { name: "Password Regex", description: "Match password rules", category: "Regex", href: "/tools/code-generator", iconName: "wand", accent: "text-red-700 bg-red-50" },
  { name: "HTTP Headers", description: "Inspect header text", category: "Network", href: "/tools/code-explainer", iconName: "message", accent: "text-slate-700 bg-slate-100" },
  { name: "URL Extractor", description: "Extract URLs from text", category: "Network", href: "/tools/code-generator", iconName: "wand", accent: "text-teal-600 bg-teal-50" },
  { name: "Ping Test", description: "Mock ping results", category: "Network", href: "/tools/code-checker", iconName: "bug", accent: "text-blue-700 bg-blue-50" },
  { name: "Traceroute", description: "Trace network hops", category: "Network", href: "/tools/code-checker", iconName: "bug", accent: "text-slate-700 bg-slate-100" },
  { name: "Domain Checker", description: "Check domain text", category: "Network", href: "/tools/code-checker", iconName: "bug", accent: "text-green-700 bg-green-50" },
  { name: "Port Scanner", description: "Scan port lists", category: "Network", href: "/tools/code-checker", iconName: "bug", accent: "text-slate-700 bg-slate-100" },
  { name: "Subdomain Finder", description: "Find subdomain names", category: "Network", href: "/tools/code-generator", iconName: "wand", accent: "text-indigo-700 bg-indigo-50" },
  { name: "HTTP Status Checker", description: "Check status codes", category: "Network", href: "/tools/code-checker", iconName: "bug", accent: "text-cyan-700 bg-cyan-50" },
  { name: "Redirect Checker", description: "Inspect redirects", category: "Network", href: "/tools/code-explainer", iconName: "message", accent: "text-orange-700 bg-orange-50" },
  { name: "DNS Propagation", description: "Check DNS spread", category: "Network", href: "/tools/code-checker", iconName: "bug", accent: "text-violet-700 bg-violet-50" },
  { name: "Whois Lookup", description: "Lookup domain records", category: "Network", href: "/tools/code-explainer", iconName: "message", accent: "text-slate-700 bg-slate-100" },
  { name: "IP Information", description: "Inspect IP details", category: "Network", href: "/tools/code-explainer", iconName: "message", accent: "text-blue-700 bg-blue-50" },
  { name: "DNS Record Viewer", description: "View DNS records", category: "Network", href: "/tools/code-explainer", iconName: "message", accent: "text-cyan-700 bg-cyan-50" },
  { name: "URL Parser", description: "Parse URL parts", category: "Network", href: "/tools/code-explainer", iconName: "message", accent: "text-teal-700 bg-teal-50" },
  { name: "Query String Parser", description: "Parse query params", category: "Network", href: "/tools/code-explainer", iconName: "message", accent: "text-green-700 bg-green-50" },
  { name: "IPv4 Converter", description: "Convert IPv4 values", category: "Network", href: "/tools/code-converter", iconName: "code", accent: "text-blue-700 bg-blue-50" },
  { name: "MAC Address Lookup", description: "Inspect MAC prefixes", category: "Network", href: "/tools/code-explainer", iconName: "message", accent: "text-slate-700 bg-slate-100" },
  { name: "APA Citation Generator", description: "Draft APA citations", category: "Text", href: "/tools/code-generator", iconName: "fileText", accent: "text-blue-700 bg-blue-50" },
  { name: "Character Remover", description: "Remove chosen chars", category: "Text", href: "/tools/comment-remover", iconName: "eraser", accent: "text-rose-600 bg-rose-50" },
  { name: "Duplicate Line Remover", description: "Remove repeated lines", headerDescription: "Paste your text on the left to remove duplicate lines. The first occurrence of each line is kept and subsequent duplicates are removed, preserving the original order.", category: "Text", href: "/tools/comment-remover", iconName: "eraser", accent: "text-emerald-700 bg-emerald-50" },
  { name: "Duplicate Word Finder", description: "Find repeated words", category: "Text", href: "/tools/code-checker", iconName: "bug", accent: "text-orange-700 bg-orange-50" },
  { name: "Em Dash Remover", description: "Replace em dashes", category: "Text", href: "/tools/code-converter", iconName: "eraser", accent: "text-amber-700 bg-amber-50" },
  { name: "Find and Replace Text", description: "Replace text matches", category: "Text", href: "/tools/code-converter", iconName: "code", accent: "text-cyan-700 bg-cyan-50" },
  { name: "Text Splitter", description: "Split text into lines", category: "Text", href: "/tools/code-converter", iconName: "fileText", accent: "text-blue-700 bg-blue-50" },
  { name: "Text Joiner", description: "Join lines into text", category: "Text", href: "/tools/code-converter", iconName: "fileText", accent: "text-green-700 bg-green-50" },
  { name: "Text Escape Tool", description: "Escape text characters", category: "Text", href: "/tools/code-converter", iconName: "code", accent: "text-orange-700 bg-orange-50" },
  { name: "Text Beautifier", description: "Clean and beautify text", category: "Text", href: "/tools/code-converter", iconName: "wand", accent: "text-purple-700 bg-purple-50" },
  { name: "Text Line Length Filter", description: "Filter lines by length", category: "Text", href: "/tools/code-checker", iconName: "fileText", accent: "text-cyan-700 bg-cyan-50" },
  { name: "Fixed Length Text Lines", description: "Wrap text to fixed length", category: "Text", href: "/tools/code-converter", iconName: "fileText", accent: "text-teal-700 bg-teal-50" },
  { name: "Punctuation Converter", description: "Convert punctuation style", category: "Text", href: "/tools/code-converter", iconName: "code", accent: "text-pink-700 bg-pink-50" },
  { name: "Key Value to Code", description: "Convert pairs to code", category: "Text", href: "/tools/code-generator", iconName: "code", accent: "text-indigo-700 bg-indigo-50" },
  { name: "Directory Tree Generator", description: "Generate directory trees", category: "Text", href: "/tools/code-generator", iconName: "fileText", accent: "text-slate-700 bg-slate-100" },
  { name: "Pinyin Converter", description: "Convert Chinese to pinyin", category: "Text", href: "/tools/code-converter", iconName: "message", accent: "text-red-700 bg-red-50" },
  { name: "Simplified Traditional Converter", description: "Convert Chinese variants", category: "Text", href: "/tools/code-converter", iconName: "message", accent: "text-amber-700 bg-amber-50" },
  { name: "camelCase Converter", description: "Convert text to camelCase", category: "Text", href: "/tools/code-converter", iconName: "code", accent: "text-teal-700 bg-teal-50" },
  { name: "PascalCase Converter", description: "Convert text to PascalCase", category: "Text", href: "/tools/code-converter", iconName: "code", accent: "text-blue-700 bg-blue-50" },
  { name: "snake_case Converter", description: "Convert text to snake_case", category: "Text", href: "/tools/code-converter", iconName: "code", accent: "text-emerald-700 bg-emerald-50" },
  { name: "kebab-case Converter", description: "Convert text to kebab-case", category: "Text", href: "/tools/code-converter", iconName: "code", accent: "text-amber-700 bg-amber-50" },
  { name: "dot.case Converter", description: "Convert text to dot.case", category: "Text", href: "/tools/code-converter", iconName: "code", accent: "text-violet-700 bg-violet-50" },
  { name: "Invisible Text Generator", description: "Create blank text", category: "Text", href: "/tools/code-generator", iconName: "wand", accent: "text-slate-700 bg-slate-100" },
  { name: "NATO Phonetic Alphabet Translator", description: "Spell with NATO words", category: "Text", href: "/tools/code-converter", iconName: "message", accent: "text-indigo-700 bg-indigo-50" },
  { name: "Online Notepad", description: "Plain text scratchpad", category: "Text", href: "/tools/code-generator", iconName: "fileText", accent: "text-green-700 bg-green-50" },
  { name: "Online Sentence Counter", description: "Count sentences", category: "Text", href: "/tools/code-checker", iconName: "fileText", accent: "text-teal-700 bg-teal-50" },
  { name: "Phonetic Spelling Tool", description: "Spell words aloud", category: "Text", href: "/tools/code-converter", iconName: "message", accent: "text-purple-700 bg-purple-50" },
  { name: "Pig Latin Translator", description: "Convert to Pig Latin", category: "Text", href: "/tools/code-converter", iconName: "message", accent: "text-pink-700 bg-pink-50" },
  { name: "Plain Text Converter", description: "Strip rich text", category: "Text", href: "/tools/code-converter", iconName: "fileText", accent: "text-slate-700 bg-slate-100" },
  { name: "Markdown Table Generator", description: "Create Markdown tables", category: "Text", href: "/tools/code-generator", iconName: "fileText", accent: "text-blue-700 bg-blue-50" },
  { name: "Aesthetic Text", description: "Add spaced aesthetic style", category: "Font Styles", href: "/tools/code-converter", iconName: "wand", accent: "text-pink-700 bg-pink-50" },
  { name: "Big Text Generator", description: "Make text big and spaced", category: "Font Styles", href: "/tools/code-generator", iconName: "wand", accent: "text-orange-700 bg-orange-50" },
  { name: "Bold Text Generator", description: "Create bold Unicode text", category: "Font Styles", href: "/tools/code-generator", iconName: "wand", accent: "text-slate-700 bg-slate-100" },
  { name: "Bubble Text Generator", description: "Create circled text", category: "Font Styles", href: "/tools/code-generator", iconName: "wand", accent: "text-sky-700 bg-sky-50" },
  { name: "Cursed Text Tool", description: "Create glitchy text", category: "Font Styles", href: "/tools/code-generator", iconName: "wand", accent: "text-red-700 bg-red-50" },
  { name: "Cute Font Generator", description: "Make cute styled text", category: "Font Styles", href: "/tools/code-generator", iconName: "wand", accent: "text-rose-700 bg-rose-50" },
  { name: "Discord Font Generator", description: "Style text for Discord", category: "Font Styles", href: "/tools/code-generator", iconName: "wand", accent: "text-indigo-700 bg-indigo-50" },
  { name: "Double-Struck Text", description: "Create double-struck text", category: "Font Styles", href: "/tools/code-generator", iconName: "wand", accent: "text-blue-700 bg-blue-50" },
  { name: "Facebook Font Generator", description: "Style text for Facebook", category: "Font Styles", href: "/tools/code-generator", iconName: "wand", accent: "text-blue-700 bg-blue-50" },
  { name: "Fancy Text Generator", description: "Create fancy Unicode text", category: "Font Styles", href: "/tools/code-generator", iconName: "wand", accent: "text-purple-700 bg-purple-50" },
  { name: "Fonts for Instagram", description: "Style text for Instagram", category: "Font Styles", href: "/tools/code-generator", iconName: "wand", accent: "text-fuchsia-700 bg-fuchsia-50" },
  { name: "Gothic Text", description: "Create gothic text style", category: "Font Styles", href: "/tools/code-generator", iconName: "wand", accent: "text-slate-700 bg-slate-100" },
  { name: "Italic Text Generator", description: "Create italic Unicode text", category: "Font Styles", href: "/tools/code-generator", iconName: "wand", accent: "text-teal-700 bg-teal-50" },
  { name: "Mirror Text Generator", description: "Reverse mirrored text", category: "Font Styles", href: "/tools/code-generator", iconName: "wand", accent: "text-cyan-700 bg-cyan-50" },
  { name: "Slash Text Generator", description: "Add slash overlay text", category: "Font Styles", href: "/tools/code-generator", iconName: "wand", accent: "text-amber-700 bg-amber-50" },
  { name: "Small Text Generator", description: "Make tiny text", headerDescription: "Convert normal text into small Unicode-style text for bios, captions, usernames, and short social posts.", category: "Font Styles", href: "/tools/code-converter", iconName: "wand", accent: "text-violet-700 bg-violet-50" },
  { name: "Stacked Text Generator", description: "Create stacked text", category: "Font Styles", href: "/tools/code-generator", iconName: "wand", accent: "text-green-700 bg-green-50" },
  { name: "Strikethrough Text Generator", description: "Strike through text", category: "Font Styles", href: "/tools/code-generator", iconName: "wand", accent: "text-red-700 bg-red-50" },
  { name: "Subscript Generator", description: "Create subscript text", category: "Font Styles", href: "/tools/code-generator", iconName: "wand", accent: "text-blue-700 bg-blue-50" },
  { name: "Superscript Generator", description: "Create superscript text", category: "Font Styles", href: "/tools/code-generator", iconName: "wand", accent: "text-violet-700 bg-violet-50" },
  { name: "TikTok Font Generator", description: "Style text for TikTok", category: "Font Styles", href: "/tools/code-generator", iconName: "wand", accent: "text-pink-700 bg-pink-50" },
  { name: "Twitter Font Generator", description: "Style text for Twitter", category: "Font Styles", href: "/tools/code-generator", iconName: "wand", accent: "text-sky-700 bg-sky-50" },
  { name: "Typewriter Text", description: "Create typewriter text", category: "Font Styles", href: "/tools/code-generator", iconName: "wand", accent: "text-slate-700 bg-slate-100" },
  { name: "Underline Text Generator", description: "Underline each character", category: "Font Styles", href: "/tools/code-generator", iconName: "wand", accent: "text-cyan-700 bg-cyan-50" },
  { name: "Unicode Text Converter", description: "Convert text to Unicode escapes", category: "Font Styles", href: "/tools/code-converter", iconName: "code", accent: "text-purple-700 bg-purple-50" },
  { name: "Unicode to Text Converter", description: "Decode Unicode escapes", category: "Font Styles", href: "/tools/code-converter", iconName: "message", accent: "text-purple-700 bg-purple-50" },
  { name: "Upside Down Text", description: "Flip text upside down", category: "Font Styles", href: "/tools/code-generator", iconName: "wand", accent: "text-orange-700 bg-orange-50" },
  { name: "WhatsApp Font Generator", description: "Style text for WhatsApp", category: "Font Styles", href: "/tools/code-generator", iconName: "wand", accent: "text-green-700 bg-green-50" },
  { name: "Wide Text Generator", description: "Create wide fullwidth text", category: "Font Styles", href: "/tools/code-generator", iconName: "wand", accent: "text-blue-700 bg-blue-50" },
  { name: "Zalgo Text Generator", description: "Create intense glitch text", category: "Font Styles", href: "/tools/code-generator", iconName: "wand", accent: "text-red-700 bg-red-50" },
  { name: "Remove Line Breaks", description: "Join broken lines", category: "Text", href: "/tools/comment-remover", iconName: "eraser", accent: "text-blue-700 bg-blue-50" },
  { name: "Remove Text Formatting", description: "Clean pasted text", category: "Text", href: "/tools/comment-remover", iconName: "eraser", accent: "text-violet-700 bg-violet-50" },
  { name: "Remove Underscores", description: "Replace underscores", category: "Text", href: "/tools/code-converter", iconName: "eraser", accent: "text-cyan-700 bg-cyan-50" },
  { name: "Repeat Text Generator", description: "Repeat text lines", category: "Text", href: "/tools/code-generator", iconName: "wand", accent: "text-orange-700 bg-orange-50" },
  { name: "Reverse Text Generator", description: "Reverse text", category: "Text", href: "/tools/code-converter", iconName: "code", accent: "text-fuchsia-700 bg-fuchsia-50" },
  { name: "Roman Numeral Dates", description: "Convert year numbers", category: "Text", href: "/tools/code-converter", iconName: "code", accent: "text-red-700 bg-red-50" },
  { name: "Sentence Case Converter", description: "Fix sentence case", category: "Text", href: "/tools/code-converter", iconName: "code", accent: "text-green-700 bg-green-50" },
  { name: "Sort Words Alphabetically", description: "Sort words A-Z", category: "Text", href: "/tools/code-checker", iconName: "fileText", accent: "text-indigo-700 bg-indigo-50" },
  { name: "Title Case Converter", description: "Make title case", category: "Text", href: "/tools/code-converter", iconName: "code", accent: "text-blue-700 bg-blue-50" },
  { name: "Whitespace Remover", description: "Remove extra spaces", category: "Text", href: "/tools/comment-remover", iconName: "eraser", accent: "text-slate-700 bg-slate-100" },
  { name: "Wingdings Translator", description: "Map text symbols", category: "Text", href: "/tools/code-converter", iconName: "message", accent: "text-purple-700 bg-purple-50" },
  { name: "Word Cloud Generator", description: "List top words", category: "Text", href: "/tools/code-generator", iconName: "wand", accent: "text-cyan-700 bg-cyan-50" },
  { name: "Word Frequency Counter", description: "Count word usage", category: "Text", href: "/tools/code-checker", iconName: "fileText", accent: "text-emerald-700 bg-emerald-50" }
];

export const directoryTools = rawDirectoryTools.map((tool) => ({
  ...tool,
  href: `/${directoryToolSlug(tool.name)}`
}));

export const directoryToolBySlug = Object.fromEntries(
  directoryTools.map((tool) => [directoryToolSlug(tool.name), tool])
) as Record<string, DirectoryTool>;

export const frequentTools = directoryTools.slice(0, 20);
