import type { ToolConfig } from "@/lib/tools";

export type MockRequest = {
  tool: ToolConfig;
  input: string;
  sourceLanguage: string;
  targetLanguage: string;
};

function stripCommonComments(input: string) {
  return input
    .replace(/\/\*[\s\S]*?\*\//g, "")
    .replace(/^\s*\/\/.*$/gm, "")
    .replace(/^\s*#.*$/gm, "")
    .replace(/^\s*--.*$/gm, "")
    .replace(/\n{3,}/g, "\n\n")
    .trim();
}

export async function mockResult({ tool, input, sourceLanguage, targetLanguage }: MockRequest) {
  await new Promise((resolve) => setTimeout(resolve, 650));

  const trimmed = input.trim();
  const preview = trimmed.length > 900 ? `${trimmed.slice(0, 900)}\n...` : trimmed;

  switch (tool.slug) {
    case "code-converter":
      return `// Mock conversion from ${sourceLanguage} to ${targetLanguage}\n// Replace mockResult() with your API route when ready.\n\n${preview || "// Paste source code to convert."}`;
    case "code-generator":
      return `// Mock ${targetLanguage} code generated from your prompt\n// Prompt: ${preview || "Describe the code you want."}\n\nfunction exampleTask() {\n  return "Generated placeholder";\n}`;
    case "code-explainer":
      return `Summary\nThis mock explanation describes the selected ${sourceLanguage} snippet.\n\nKey points\n- Identifies the main control flow.\n- Notes important inputs and outputs.\n- Leaves room for a future AI-powered explanation.\n\nSnippet preview\n${preview || "No code provided."}`;
    case "comment-remover":
      return stripCommonComments(trimmed) || "No comments or code were found in the input.";
    case "code-checker":
      return `Code check report for ${sourceLanguage}\n\n- No real static analysis is running yet.\n- The future API layer can return bugs, risk levels, and suggested patches here.\n- Keep examples small for faster review.\n\nReviewed preview\n${preview || "No code provided."}`;
    case "code-to-pdf":
      return `Code Document\nLanguage: ${sourceLanguage}\nGenerated by: CodeTools AI\n\n${preview || "Paste code to prepare a printable document."}\n\nNote: This MVP downloads text. A later API route can render a real PDF.`;
    default:
      return preview;
  }
}
